# Generated by Django 2.1.5 on 2019-01-10 15:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Nakitus',
                'verbose_name_plural': 'Nakitusta',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Nimi')),
                ('url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True, verbose_name='Kuvaus')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Järjestäjän sähköposti')),
                ('active', models.BooleanField(default=False, help_text='Ilmoittautuminen auki', verbose_name='Aktiivinen')),
                ('secret_question', models.CharField(blank=True, help_text='Kysymys ilmoittautujille, jätä tyhjäksi jos ei tarvita.', max_length=512, verbose_name='Kysymys ilmoittautujille')),
                ('secret_answer', models.CharField(blank=True, help_text='Oikea vastaus kysymykseen', max_length=512, verbose_name='Vastaus kysymykseen')),
                ('public_tasks', models.BooleanField(default=True, help_text='Näytetäänkö nakit julkisesti', verbose_name='Julkiset nakit')),
                ('ask_email', models.BooleanField(default=False, help_text='Kysytäänkö ilmoittautumisessa sähköpostiosoitetta', verbose_name='Kysy sähköpostiosoite')),
                ('ask_phone', models.BooleanField(default=False, help_text='Kysytäänkö ilmoittautumisessa puhelinnumero', verbose_name='Kysy puhelinnumero')),
            ],
            options={
                'verbose_name': 'Tapahtuma',
                'verbose_name_plural': 'Tapahtumat',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Nimi')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Sähköpostiosoite')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Puhelinnumero')),
                ('modifycode', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Muokkauskoodi')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Event', verbose_name='Tapahtuma')),
            ],
            options={
                'verbose_name': 'Ilmoittautunut',
                'verbose_name_plural': 'Ilmoittautuneet',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Nimi')),
                ('description', models.TextField(blank=True, verbose_name='Kuvaus')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Event', verbose_name='Tapahtuma')),
            ],
            options={
                'verbose_name': 'Ominaisuus',
                'verbose_name_plural': 'Ominaisuudet',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Nimi')),
                ('description', models.TextField(blank=True, verbose_name='Kuvaus')),
                ('points', models.IntegerField(default=100, verbose_name='Pisteet')),
                ('min_assignees', models.PositiveIntegerField(default=1, help_text='Nakitettavien vähimmäismäärä', verbose_name='Nakitettavien määrä')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Event', verbose_name='Tapahtuma')),
                ('required_tags', models.ManyToManyField(blank=True, help_text='Nakitettaville pakolliset ominaisuudet', to='tasks.Tag', verbose_name='Vaaditut ominaisuudet')),
            ],
            options={
                'verbose_name': 'Nakki',
                'verbose_name_plural': 'Nakit',
            },
        ),
        migrations.AddField(
            model_name='person',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Ilmoittautuneen ominaisuudet', to='tasks.Tag', verbose_name='Ominaisuudet'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Person'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Task'),
        ),
    ]
